name: Release

permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ["1.23"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Build
        run: sh build.sh ${GITHUB_REF##*/}
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
