name: Test

permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.23"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install tools
        run: curl --version
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 30
          command: go test -v ./pkg/...
      - name: Test with coverage
        if: matrix.os == 'ubuntu-latest'
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./pkg/...
      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
      - name: End to end test
        if: matrix.os == 'ubuntu-latest'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 30
          command: make e2e
